exasol/script-languages

- tests/lib/exatest/__init__.py
Sometimes (observed in ubuntu 18.04) pyodbc resolves "localhost" to IPv6 ::1 instead to 127.0.0.1. This workaround resolves the hostname in python via the module socket which seems to resolve per default to IPv4.
> Workaround for pyodbc's hostname resolution

- google-cloud-build/setup-scripts/create_encrypted_docker_password.sh
- google-cloud-build/setup-scripts/create_encrypted_github_token.sh
- google-cloud-build/setup-scripts/create_encryption_key.sh
- google-cloud-build/setup-scripts/deploy-github-status-notifications.sh
Closes Bug #64 and #65, because they are related
> Bug/64,65: Fix project in deploy-github-status-notifications.sh

- google-cloud-build/.env/env.template.yaml
- google-cloud-build/setup-scripts/copy_config.sh
- google-cloud-build/setup-scripts/create_buckets.sh
- google-cloud-build/setup.sh
> CI/68: Copy CI Setup config in .env to config bucket

- exaudfclient/base/build_local_all.sh
- exaudfclient/base/exaudflib/BUILD
- exaudfclient/base/javacontainer/BUILD
- exaudfclient/base/python/python2/BUILD
- exaudfclient/base/python/python3/BUILD
- flavors/python3-ds-EXASOL-6.0.0/flavor_base/build_deps/Dockerfile
- flavors/python3-ds-EXASOL-6.0.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python3-ds-EXASOL-6.1.0/flavor_base/build_deps/Dockerfile
- flavors/python3-ds-EXASOL-6.1.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python3-ds-cuda-preview-EXASOL-6.1.0/flavor_base/build_deps/Dockerfile
- flavors/python3-ds-cuda-preview-EXASOL-6.1.0/flavor_base/build_deps/packages/apt_get_packages
> Add alwayslink to cc_library and pin bazel to version 1.0.0

- flavors/python3-ds-EXASOL-6.0.0/flavor_base/build_deps/Dockerfile
- flavors/python3-ds-EXASOL-6.0.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python3-ds-EXASOL-6.1.0/flavor_base/build_deps/Dockerfile
- flavors/python3-ds-EXASOL-6.1.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python3-ds-cuda-preview-EXASOL-6.1.0/flavor_base/build_deps/Dockerfile
- flavors/python3-ds-cuda-preview-EXASOL-6.1.0/flavor_base/build_deps/packages/apt_get_packages
solves https://github.com/exasol/script-languages/issues/89
> Download bazel dep-package from Github releases

- google-cloud-build/ci-scripts/build_branch.yaml
- google-cloud-build/ci-scripts/build_pull_request.yaml
- google-cloud-build/ci-scripts/export.yaml
- google-cloud-build/ci-scripts/rebuild_branch.yaml
- google-cloud-build/ci-scripts/release.yaml
- google-cloud-build/ci-scripts/scripts/create_github_release.sh
- google-cloud-build/ci-scripts/scripts/test.sh
- Fix path to the exported container
- Adapt timeouts of CI-scripts
- Add [skip tests] commit message flag to build script
> Improve and fix google-cloud-build config

- exaudfclient/base/BUILD
- exaudfclient/base/create_binary_wrapper_valgrind.sh
- exaudfclient/base/create_binary_wrapper_valgrind_massif.sh
- exaudfclient/base/exaudflib/exaudflib.h
- exaudfclient/base/variables.bzl
and add valgrind wrapper for the exaudfclient
> Fix memory leak in metadata pimpl 

- exaslct_src/cli/commands/upload.py
- exaslct_src/lib/upload_container_base_task.py
- exaslct_src/lib/upload_containers_parameter.py
> Fixes issue #109

- exaudfclient/base/javacontainer/ExaIteratorImpl.java
- tests/test/java/bugs.py
solves https://github.com/exasol/script-languages-release/issues/31
> Java EMITS UDF Scripts cannot emit null

- exaudfclient/base/.bazelrc
- exaudfclient/base/debug_message.h
- exaudfclient/base/exaudflib/exaudflib.cc
> Improve shutdown handling of the UDFClient in error cases

- exaudfclient/base/javacontainer/ExaIteratorImpl.java
> EXAUDFClient: Optimize code ordering for bugfix of #113 to reduce performance degradation

- exaudfclient/base/python/exascript_python_wrap.py
- tests/lib/udf/__init__.py
- tests/test/python3/dataframe.py
closes #128 and refactors the Python UDF Dataframe tests
> Fix Python UDF Bug with reset after get_dataframe reaches the end of the iterator

- .github/workflows/check_error_codes.yml
- exaudfclient/base/debug_message.h
- exaudfclient/base/exaudflib/exaudflib.cc
- exaudfclient/base/exaudflib/exaudflib.h
- find_duplicate_error_codes.sh
- find_error_codes.sh
- Introduce error codes into exaudflib.cc
- Add scripts to find duplicate error codes
- Add Github action to check error codes
> Introduce error codes into exaudflib

- flavors/python3-ds-EXASOL-6.0.0/flavor_base/release/Dockerfile
- flavors/python3-ds-EXASOL-6.1.0/flavor_base/release/Dockerfile
- flavors/python3-ds-cuda-preview-EXASOL-6.1.0/flavor_base/release/Dockerfile
Fixes https://github.com/exasol/script-languages-release/issues/84
> Copy /var from language_deps and flavor_customization to release step

- .github/workflows/check_if_submodules_head_are_ancestors_of_origin_master.yaml
- scripts/check_if_submodules_head_are_ancestors_of_origin_master.sh
Solves https://github.com/exasol/script-languages-release/issues/87
> Add pull-request blocker which checks if the HEAD of submodules is at a ancestor of origin/master

- flavors/python3-ds-EXASOL-6.0.0/flavor_customization/Dockerfile
Fixes https://github.com/exasol/script-languages-release/issues/82
> Fix python3 binary for python3-ds-EXASOL-6.0.0 flavor_customization install script

- google-cloud-build/triggers/build_branch.json.jinja2
helps with https://github.com/exasol/script-languages-release/issues/99
> Trigger rebuild automatically for branches with the prefix `rebuild/`

- ext/scripts/install_scripts/install_via_r_remotes.pl
Fixes https://github.com/exasol/script-languages-release/issues/104
> Fix failed install via r versions

- udf-script-signature-generator/udf-script-signature-generator.html
> Update Exasol logo for the UDF Signature Generator

- exaslct_src/exaslct/lib/tasks/export/export_container_base_task.py
- exaslct_src/test/test_docker_export.py
Part of https://github.com/exasol/script-languages-release/issues/127
> Fix checksum file extension for exported container

- exaslct_src/exaslct/cli/commands/upload.py
- exaslct_src/test/test_docker_upload.py
Part of https://github.com/exasol/script-languages-release/issues/160
> Make the --path-in-bucket commandline argument optional for the upload command

- exaslct_src/exaslct/lib/utils/docker_utils.py
Part of https://github.com/exasol/script-languages-release/issues/64
> Fix comparision in find_images_by_tag in docker_utils.py

- .gitignore
- google-cloud-build/ci-scripts/build_branch.yaml
- google-cloud-build/ci-scripts/build_master_branch.yaml
- google-cloud-build/ci-scripts/build_pull_request.yaml
- google-cloud-build/ci-scripts/export.yaml
- google-cloud-build/ci-scripts/rebuild_branch.yaml
- google-cloud-build/ci-scripts/release.yaml
- google-cloud-build/ci-scripts/test_branch_exaslct.yaml
> #173 Increased queueTtl for google build

- flavors/python-3.6-data-science-EXASOL-6.2.0/flavor_base/base_test_build_run/Dockerfile
- flavors/python-3.6-data-science-EXASOL-6.2.0/flavor_base/build_run/Dockerfile
- flavors/python-3.6-data-science-EXASOL-6.2.0/flavor_base/flavor_test_build_run/Dockerfile
- flavors/python-3.6-data-science-EXASOL-6.2.0/flavor_base/release/Dockerfile
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/base_test_build_run/Dockerfile
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/build_run/Dockerfile
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/flavor_test_build_run/Dockerfile
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/release/Dockerfile
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/base_test_build_run/Dockerfile
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/build_run/Dockerfile
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/flavor_test_build_run/Dockerfile
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/release/Dockerfile
Related to https://github.com/exasol/script-languages-release/issues/228
> Fix error caused by consecutive COPY in the Dockefiles

- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
libssl was changed to 1.1.1-1ubuntu2.118.04.10.
> #312: Updated libssl.

- ext/scripts/install_scripts/install_via_r_remotes.pl
The previous version of the script failed when the dependency list was too long, because it passed the generated install R script via command line to Rscript.
Related to https://github.com/exasol/script-languages-release/issues/317
> Using temporary file for the install script in install_via_r_remotes

- tests/test/standard-flavor/7.1/available-packages-sagemaker-sdk.py
> #366 Added Sagemaker into Standard flavours 7.1.0

- tests/test/r/network.py
Check if RCurl package is installed before running test.
> #386: Fix Network Test for r-4-minimal

- .github/markdown_check_config.json
- .github/workflows/check_markdown_links.yaml
- exaudfclient/base/README.md
Part of https://github.com/exasol/script-languages-release/issues/225
> #225: Fix broken links and add markdown link checker

- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
Related to https://github.com/exasol/script-languages-release/issues/541
> #541: Update packages

- ext/scripts/tests/install_scripts/run_pip_tests.sh
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- ext/scripts/tests/install_scripts/test_files/pip/pip_version_syntax
- ext/scripts/tests/install_scripts/test_files/pip/with_versions/some_missing_versions
- ext/scripts/tests/install_scripts/test_files/pip/with_versions/with_urls
- ext/scripts/tests/install_scripts/test_files/pip/with_versions/with_urls_some_missing_versions
- ext/scripts/tests/install_scripts/test_files/pip/without_versions
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/596
> #596: Updated packages

- scripts/generate_package_diffs_for_flavors/generate_package_diffs_for_flavors.py
Related to https://github.com/exasol/script-languages-release/issues/601
> #601: Sorted packages in package diff alphabetically

- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
Related to https://github.com/exasol/script-languages-release/issues/613
> #613: Ignored CVE-2022-29581

- .github/workflows/check_aws_buildspec.yaml
- .github/workflows/check_bazel_tests.yml
- .github/workflows/check_error_codes.yml
- .github/workflows/check_if_submodules_head_are_ancestors_of_origin_master.yaml
- .github/workflows/check_markdown_links.yaml
- .github/workflows/check_starter_scripts.yaml
- .github/workflows/shellcheck.yaml
- .github/workflows/test_package_management_scripts.yaml
- exaslct_scripts/exaslct.sh
- poetry.lock
- pyproject.toml
- tests/test/java/test_hadoop_etl_udfs.py
- tests/test/standard-flavor/all/paramiko_connection_test.py
- tests/test/standard-flavor/all/pysftp_connection_test.py
Related to https://github.com/exasol/script-languages-release/issues/616
> #616: Performed login to dockerhub for specific tests

- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- poetry.lock
Related to https://github.com/exasol/script-languages-release/issues/621
> #621: Fixed CVE-2022-21499

- aws-code-build/ci/buildspec.yaml
- poetry.lock
- pyproject.toml
Related to https://github.com/exasol/script-languages-release/issues/631
> #631: Updated script-languages-container-ci-setup and script-languages-container-ci

- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
Related to https://github.com/exasol/script-languages-release/issues/636
> #636: Updated Ubuntu packages

- tests/Dockerfile
Related to https://github.com/exasol/script-languages-release/issues/588
> #588: Removed virtualschema-jdbc-adapter.jar

- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/654
> #654: Updated Ubuntu packages

- tests/Dockerfile
- tests/requirements.txt
- tests/test/standard-flavor/7.0/available-packages.py
- tests/test/standard-flavor/7.1/available-packages-azure-sdk.py
- tests/test/standard-flavor/7.1/available-packages-gcp-sdk.py
- tests/test/standard-flavor/7.1/available-packages-sagemaker-sdk.py
- tests/test/standard-flavor/8.0/available-packages.py
Related to https://github.com/exasol/script-languages-release/issues/572
> 572: Refactor package import tests

- tests/test/standard-flavor/7.0/available-packages.py
- tests/test/standard-flavor/7.1/available-packages-azure-sdk.py
- tests/test/standard-flavor/7.1/available-packages-gcp-sdk.py
- tests/test/standard-flavor/7.1/available-packages-sagemaker-sdk.py
- tests/test/standard-flavor/8.0/available-packages.py
related to https://github.com/exasol/script-languages-release/issues/572
> #572: fix for refactor package import tests

- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- ext/scripts/tests/install_scripts/test_files/r/versions/with_versions/all_versions_specified
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/659
> #659: Updated curl

- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
Related to https://github.com/exasol/script-languages-release/issues/662
> #662: Updated libssl-dev

- .github/workflows/check_package_diffs.yaml
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/derived_from
- scripts/generate_package_diffs_for_flavors/generate_package_diffs_for_flavors.py
related to https://github.com/exasol/script-languages-release/issues/666
>  #666: Make package diffs more robust for CI

- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/671
> #671: Updated git packages

- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/674
> #674: Updated Python and Python-dev

- poetry.lock
- pyproject.toml
- scripts/check_release.py
- scripts/check_release.sh
https://github.com/exasol/script-languages-release/issues/677
> #677: Improved poetry project structure

- flavors/template-Exasol-all-python-3.8-conda/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/build_deps/packages/conda_packages
related to https://github.com/exasol/script-languages-release/issues/686
> #686: Fix crash of Bazel on conda flavor

- .github/workflows/check_package_diffs.yaml
related to https://github.com/exasol/script-languages-release/issues/692
> #692: Stopped running check package diff workflow on master

- .github/workflows/check_package_diffs.yaml
related to https://github.com/exasol/script-languages-release/issues/703
> #703: Fixed package diff ignore for master

- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/710
fixes  CVE-2022-35252
> #710: Updated curl

- ext/scripts/tests/install_scripts/run_ppa_tests.sh
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages_python
related to https://github.com/exasol/script-languages-release/issues/713
> #713: Update Python3.7

- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages_python
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/720
> #720: Updated ubuntu dependencies in all flavors

- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/720
> Updated unzip for Ubuntu20.04

- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/723
> #723: Updated curl

- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- poetry.lock
related to https://github.com/exasol/script-languages-release/issues/745
> 745: Updated ubuntu python packages

- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/748
> #748: Updated git

- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/756
> #756: Updated Ubuntu packages

- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/759
> #759: Updated Ubuntu packages

- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/udfclient_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/udfclient_deps/packages/conda_packages
- scripts/update_apt_package_in_package_list.sh
related to https://github.com/exasol/script-languages-release/issues/762
> #762: Update conda/ubuntu packages

- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
Related to https://github.com/exasol/script-languages-release/issues/775
> #775: Update dependencies

- exaslct_scripts/exaslct.sh
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/785
> #785: Updated ubuntu packages.

- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
Related to https://github.com/exasol/script-languages-release/issues/789
> #789: Update packages

- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
Related to https://github.com/exasol/script-languages-release/issues/800
> #800: Update ubuntu packages

- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
Related to https://github.com/exasol/script-languages-release/issues/803
> #803: Update Ubuntu packages

- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- poetry.lock
Related to https://github.com/exasol/script-languages-release/issues/814
> #814: Update packages

- test_container/tests/test/pandas/all/emit_dtypes.py
Related to https://github.com/exasol/script-languages-release/issues/793
Fix for https://github.com/exasol/script-languages/pull/357
> Fix error codes in tests

- flavors/template-Exasol-all-python-3.8-conda/flavor_base/build_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/udfclient_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/build_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/udfclient_deps/packages/conda_packages
Related to https://github.com/exasol/script-languages-release/issues/793
Fix for https://github.com/exasol/script-languages/pull/357
> #793: Add pyarrow to template python 3.8 conda flavors

- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
Related to https://github.com/exasol/script-languages-release/issues/822
> #822: Updated apt-packages

- flavors/template-Exasol-all-python-3.8-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/udfclient_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/udfclient_deps/packages/conda_packages
Related to https://github.com/exasol/script-languages-release/issues/831
> #831: Update conda flavors to cryptography 41.0.3

- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/security_scan/.trivyignore
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/security_scan/.trivyignore
> Address CVE-2023-4622, CVE-2023-4623, CVE-2023-4921

- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
Related to https://github.com/exasol/script-languages-release/issues/847
> #848: Updated libssl-dev

- test_container/tests/test/standard-flavor/all/import_modules.py
- test_container/tests/test/standard-flavor/all/pyexasol.py
Related to https://github.com/exasol/script-languages-release/issues/808
Related to https://github.com/exasol/script-languages-release/issues/836
> #808: Update flavor standard-EXASOL-7.1.0 to Ubuntu 20.04

- ext/scripts/install_scripts/install_python2.7_pip.sh
- ext/scripts/install_scripts/install_python3.6_pip.sh
- ext/scripts/install_scripts/install_python3.7_pip.sh
- ext/scripts/tests/Dockerfile
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
Related to https://github.com/exasol/script-languages-release/issues/850
> #850: Fix package management tests by updating Ubuntu 20.04

- exaudfclient/base/.bazelrc
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/python3_pip_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/build_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/udfclient_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/build_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/udfclient_deps/packages/conda_packages
Related to https://github.com/exasol/script-languages-release/issues/854
> #854: Update pyarrow to fix CVE-2023-47248

- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
- scripts/update_apt_package_in_package_list.sh
Related to https://github.com/exasol/script-languages-release/issues/861
> #861: Updated Packages

- exaslct_scripts/exaslct.sh
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/base_test_deps/packages/apt_get_packages
- poetry.lock
- pyproject.toml
Related to https://github.com/exasol/script-languages-release/issues/861
> #861: Updated binutils and increase version in pyproject.toml

- test_container/tests/test/python3/all/sys_executable.py
- test_container/tests/test/standard-flavor/all/pyexasol.py
Related to https://github.com/exasol/script-languages-release/issues/870
> #870: Added tests for pyexasol export/import and sys.executable

- scripts/generate_package_diffs_for_flavors/generate_package_diffs_for_flavors.py
- test_container/tests/test/java/test_hadoop_etl_udfs.py
Related to https://github.com/exasol/script-languages-release/issues/810
>  #810: Proof of concept for java 17 #873 

- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
Related to https://github.com/exasol/script-languages-release/issues/876
> #876: Update dependencies

- .gitignore
- aws-code-build/DeveloperGuide.md
- exaudfclient/base/javacontainer/ExaWrapper.java
- find_error_codes.sh
- flavors/template-Exasol-all-python-3.10/flavor_base/udfclient_deps/packages/apt_get_packages
- test_container/build/Dockerfile
- test_container/build/deps/maven-toolchains.xml
- test_container/tests/test/java/java_modules.py
- test_container/tests/test/java/resources/java_udf/pom.xml
- test_container/tests/test/java/resources/java_udf/src/main/java/com/exasol/slc/testudf/Main.java
- test_container/tests/test/java/resources/java_udf/src/main/java/module-info.java
Related to https://github.com/exasol/script-languages-release/issues/877
Related to https://github.com/exasol/script-languages-release/issues/718: Fixes copy&paste error in error message
> Add java module tests

- flavors/template-Exasol-all-python-3.10/flavor_base/flavor_base_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/906
> #906: Updated APT package

- flavors/template-Exasol-all-python-3.10-conda/flavor_base/udfclient_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.10-cuda-conda/flavor_base/udfclient_deps/packages/conda_packages
related to https://github.com/exasol/script-languages-release/issues/908
> #908: Pinned conda package

- flavors/template-Exasol-all-python-3.10-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/udfclient_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/910
> #910: Updated apt package

- test_container/build/deps/requirements.txt
- test_container/tests/test/java/java_modules.py
- test_container/tests/test/java/test_hadoop_etl_udfs.py
- test_container/tests/test/standard-flavor/all/connect_to_exasol_with_websocket_api.py
- test_container/tests/test/standard-flavor/all/pyexasol.py
- test_container/tests/test/standard-flavor/all/row_level_security_with_websocket_api.py
related to https://github.com/exasol/script-languages-release/issues/921
> #921: Use exasol-python-test-framework 0.5.0

- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-cuda-conda/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/udfclient_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/930
> #930: Updated Packages

- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/language_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/729
> Updated packages

- exaudfclient/base/exaudflib/swig/swig_common.h
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-cuda-conda/flavor_base/build_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.10-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/language_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/956
> #956: update dependencies

- ext/scripts/security_scan/run_trivy.sh
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/language_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/962
> #962: Use Trivy cache and updated Ubuntu packages

- exaudfclient/base/javacontainer/test/cpp/javacontainer_perf_test.cc
related to https://github.com/exasol/script-languages-release/issues/982
> #982: Added a performance test for ScriptOptions parser for a single line UDF

- exaudfclient/base/script_options_parser/ctpg/script_option_lines_ctpg.cc
- exaudfclient/base/script_options_parser/ctpg/test/script_option_lines_test.cpp
https://github.com/exasol/script-languages-release/issues/993
> #993: Added escape sequence for backslash in new Script Options parser

- test_container/tests/lang/java/get_connection.sql
- test_container/tests/test/generic/get_connection.py
- test_container/tests/test/java/external_jar_files.py
- test_container/tests/test/java/general.py
- test_container/tests/test/java/java_modules.py
- test_container/tests/test/java/script_import.py
related to https://github.com/exasol/script-languages-release/issues/988
> #988: Adapted Java integration tests for new ScriptOptions parser

- flavors/template-Exasol-all-java-17/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-java-17/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/build_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/1006
> #1006: Updated Dependencies on top of 8.4.0

- ext/scripts/install_scripts/install_via_conda.pl
- flavors/template-Exasol-all-python-3.10-cuda-conda/flavor_base/build_deps/packages/conda_packages
> #958: Fix conda version conflict

- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-java-17/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-java-17/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/language_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/1019
> #109: Updated dependencies

- aws-code-build/ci/buildspec.yaml
- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/security_scan/trivy.rego
- flavors/template-Exasol-all-java-17/flavor_base/security_scan/trivy.rego
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/security_scan/trivy.rego
- flavors/template-Exasol-all-python-3.10/flavor_base/security_scan/trivy.rego
related to https://github.com/exasol/script-languages-release/issues/1029
> #1029: Extended trivy rego for Kernel CVE's

- flavors/template-Exasol-all-python-3.10/flavor_base/language_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/1054
> #1054: Updated dependencies

- test_container/tests/test/pandas/all/dataframe_memory_leak.py
related to https://github.com/exasol/script-languages-release/issues/1060
> Adjusted numbers for pandas dataframe memory leak test

- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-java-17/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-java-17/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/template-Exasol-all-java-17/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/test-Exasol-8-cuda-ml/flavor_base/conda_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/1068
> #1068: Updated dependencies on top of 9.2.0

- .github/workflows/test_package_management_scripts.yaml
- ext/scripts/install_scripts/install_via_pip.pl
- ext/scripts/tests/docker_all_dependencies/Dockerfile
- ext/scripts/tests/docker_python_only/Dockerfile
- ext/scripts/tests/install_scripts/run_pip_tests.sh
- ext/scripts/tests/install_scripts/run_pip_tests_base.sh
- ext/scripts/tests/install_scripts/run_pip_tests_with_epheramal_build_tools.sh
- ext/scripts/tests/install_scripts/test_files/pip/needs_build_tools
- ext/scripts/tests/test_python_scripts_in_slim_docker.sh
- ext/scripts/tests/test_scripts_in_docker.sh
related https://github.com/exasol/script-languages-release/issues/1089
> #1089: New option which installs build tools during installation of Python packages

- exaudfclient/exaudfclient.cc
related to https://github.com/exasol/script-languages-release/issues/1098
> #1098: Allow setting script-options-parser version via cli argument

- test_container/tests/test/standard-flavor/all/python/import_modules.py
related to https://github.com/exasol/script-languages-release/issues/1101
> #1101: Remove setuptools.command.bdist_wheel from ignore list in import

- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/test-Exasol-8-cuda-ml/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/test-Exasol-8-cuda-ml/flavor_base/conda_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/1110
> #1110: Updated dependencies

- flavors/template-Exasol-all-python-3.10/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/test-Exasol-8-cuda-ml/flavor_base/language_definitions.json
related to https://github.com/exasol/script-languages-release/issues/1113
related to https://github.com/exasol/script-languages-release/issues/1114
> #1113/#1114: Added lang def json to cuda test slc and dependency updates

- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/test-Exasol-8-cuda-ml/flavor_base/conda_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/1124
> #1124: Updated dependencies on top of 9.5.1

- flavors/template-Exasol-all-python-3.10/flavor_base/build_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/1130
> #1130: Update dependencies

- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/build_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/build_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/test-Exasol-8-cuda-ml/flavor_base/build_deps/packages/conda_packages
related to https://github.com/exasol/script-languages-release/issues/1181
related to https://github.com/exasol/script-languages-release/issues/1180
> #1181: Fixed conda based flavors and update dependencies

- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/build_steps.py
- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/release/Dockerfile
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/build_steps.py
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/release/Dockerfile
- flavors/template-Exasol-all-python-3.10/flavor_base/build_steps.py
- flavors/template-Exasol-all-python-3.10/flavor_base/release/Dockerfile
- flavors/template-Exasol-all-python-3.12/flavor_base/build_steps.py
- flavors/template-Exasol-all-python-3.12/flavor_base/release/Dockerfile
- flavors/test-Exasol-8-cuda-ml/flavor_base/build_steps.py
- flavors/test-Exasol-8-cuda-ml/flavor_base/release/Dockerfile
related to https://github.com/exasol/script-languages-release/issues/1206
> #1206: Trim release docker images

- flavors/template-Exasol-all-python-3.10/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.12/flavor_base/language_deps/packages/apt_get_packages
relates to #1226
python3.10-dev | 3.10.12-1~22.04.10 | 3.10.12-1~22.04.11
python3.12-dev | 3.12.3-1ubuntu0.7 | 3.12.3-1ubuntu0.8
> #1226: Updated python 10 and 12 dependencies

- ext/scripts/tests/install_scripts/test_files/apt/with_versions/all_versions_specified
- ext/scripts/tests/install_scripts/test_files/apt/with_versions/some_missing_versions
- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/language_deps/packages/apt_get_packages
- flavors/test-Exasol-8-cuda-ml/flavor_base/conda_deps/packages/apt_get_packages
related to https://github.com/exasol/script-languages-release/issues/1264
> #1264: Updated Dependencies on top of 10.0.0
