- flavors/docs/py_dataframe.md
- src/exascript_python_wrap.py
- tests/test/python3/dataframe.py
If the user used get_dataframe() in a python udf the cache for the iterator was not emptied which lead to wrong behavior of the iterator. After using get_dataframe() without an call to next() the __getitem__ or __getattr__ method returned the first cached value. The following example shows alternately a dataframe with one row returned by get_dataframe() and a call to ctx.ID without any call to next. 
[('   ID 0   1',), ('2',), ('   ID 0   2',), ('2',), ('   ID 0   3',), ('2',), ('   ID 0   4',), ('2',), ('   ID 0   5',), ('2',), ('   ID 0   6',)]
The call ctx.ID returns everytime to '2' which is not correct. The expected ouptut would be:
[('   ID 0   1',), ('2',), ('   ID 0   2',), ('3',), ('   ID 0   3',), ('4',), ('   ID 0   4',), ('5',), ('   ID 0   5',), ('6',), ('   ID 0   6',)]
This …
> Fix mixed usage of get_dataframe() and iterator in python udfs

- exaslct
- flavors/python3-ds-EXASOL-6.0.0/flavor_base/flavor_base_deps/packages/pip3_packages
- flavors/python3-ds-EXASOL-6.1.0/flavor_base/flavor_base_deps/packages/pip3_packages
This pull request fixes bugs in the exaslct starter script for the case that exaslct doesn't get called from the repository root. Further, this pull requests fixes the tensorflow version to 1.13.1, because tensorflow 1.14.0 and probably tensorflow 2.0 raise error during import in the UDF. See, more details [here](https://github.com/exasol/script-languages/issues/43).
> Bugfixes for exaslct starter script and fixing tensorflow version to 1.13.1

- tests/test/standard-flavor/available-packages.py
- tests/test/standard-flavor/connect_to_exasol_with_websocket_api.py
linked to https://github.com/exasol/script-languages-release/issues/32
> Add test for exasol websocket-api for Python3 to standard flavor

- exaudfclient/base/BUILD
- exaudfclient/base/create_binary_wrapper_stdout_to_bucketfs.sh
- exaudfclient/base/exaudflib/exaudflib.cc
- tests/test/python/general.py
- tests/test/python/network.py
- move error handling code to function in exaudflib
- reactivate network.py tests to detect this bug
- return combined exception if run and cleanup throw exceptions
- add create_binary_wrapper_stdout_to_bucketfs for debugging
> Fix missing cleanup call after exception in run

- exaslct_src/cli/commands/__init__.py
- exaslct_src/cli/commands/build_test_container.py
- exaslct_src/cli/commands/push.py
- exaslct_src/cli/commands/push_test_container.py
- exaslct_src/cli/options.py
- exaslct_src/lib/analyze_test_container.py
- exaslct_src/lib/base/base_task.py
- exaslct_src/lib/docker_push.py
- exaslct_src/lib/docker_push_parameter.py
- google-cloud-build/.env/env.template.yaml
- google-cloud-build/ci-scripts/build_branch.yaml
- google-cloud-build/ci-scripts/build_master_branch.yaml
- google-cloud-build/ci-scripts/export.yaml
- google-cloud-build/ci-scripts/rebuild_branch.yaml
- google-cloud-build/ci-scripts/release.yaml
- google-cloud-build/ci-scripts/scripts/build.sh
- google-cloud-build/ci-scripts/scripts/build_or_pull_build_container.sh
- google-cloud-build/ci-scripts/scripts/check_build.sh
- google-cloud-build/ci-scripts/scripts/push.sh
- google-cloud-build/ci-scripts/scripts/test.sh
- google-cloud-build/ci-scripts/test_branch_exaslct.yaml
- google-cloud-build/download_config.sh
- google-cloud-build/github-status-notifications/index.js
- google-cloud-build/setup-scripts/copy_config.sh
- google-cloud-build/triggers/build_branch.json.jinja2
- google-cloud-build/triggers/build_pull_request.json.jinja2
- google-cloud-build/triggers/export.json.jinja2
- google-cloud-build/triggers/release.json.jinja2
- google-cloud-build/triggers/test_branch_exaslct.json.jinja2
- google-cloud-build/update_triggers.sh
Trigger Changes:
- Master branch and release trigger react on ci-release-test
- Fix trigger directories for build jobs
- Add repo name to the trigger name
Build Cache Changes:
- Move push to public build cache into the build jobs for the master branch
- All build trigger push to internal build cache with commit hash and without
- Pull build-container if possible or build and push it with build_or_pull_build_container.sh
- If the test-container not available in the public build cache, then build and push it to the build caches
Exaslct Tests Change:
- Fix test_branch_exaslct.yaml
- Fix github status name for exaslct tests
Additional Changes:
- Add scripts download_config.sh and update_triggers.sh
- Use parallel copy with gsutils
- Build steps which use docker, now list the local docker …
> Fixes and improvements on Google Cloud Build CI Setup

- exaudfclient/base/exaudflib/exaudflib.cc
- exaudfclient/base/javacontainer/BUILD
- exaudfclient/base/javacontainer/ExaCompiler.java
- exaudfclient/base/javacontainer/ExaConnectionInformationImpl.java
- exaudfclient/base/javacontainer/ExaIteratorImpl.java
- exaudfclient/base/javacontainer/ExaMetadataImpl.java
- exaudfclient/base/javacontainer/ExaUDFException.java
- exaudfclient/base/javacontainer/ExaWrapper.java
- exaudfclient/base/javacontainer/javacontainer.cc
- exaudfclient/base/python/exascript_python_preset_core.py
- exaudfclient/base/python/exascript_python_wrap.py
- exaudfclient/base/python/python3/python_ext_dataframe.cc
- exaudfclient/base/python/pythoncontainer.cc
- find_duplicate_error_codes.sh
- find_error_codes.sh
- find_highest_error_codes_per_module.sh
- find_next_error_code_per_module.sh
- githooks/install.sh
- githooks/pre-commit
- githooks/update_current_submodules_file.sh
- Return full but compact stack traces for user code exceptions in Java and Python UDFs
- Java stack traces now contain also causes of Exceptions
- Verbose stack frames inside the language implementations get still cleaned to make the exceptions easier to read
- Error codes now start at number 1000 (see https://softwareengineering.stackexchange.com/questions/209693/best-practices-to-create-error-codes-pattern-for-an-enterprise-project-in-c)
- Add error codes to the language implementations for Java, Python and R in the UDFClient
- Add missing error codes to exaudflib
- Introduce new name schema for error codes in exaudflib of the form [FEW]-UDF.CL.LIB-1000
- Add precommit githook which searches for duplicated error codes
- Replace abort()-calls in the language implementations with …
> Improve error message of language implementations in the UDFClient

- flavors/python3-ds-EXASOL-6.0.0/flavor_base/flavor_base_deps/packages/pip3_packages
- flavors/python3-ds-EXASOL-6.1.0/flavor_base/flavor_base_deps/packages/pip3_packages
- githooks/install.sh
- githooks/install_recursive.sh
- githooks/pre-commit
- githooks/pre-push
- githooks/prohibit_commit_to_master.sh
- google-cloud-build/download_config.sh
- Pin tensorflow_hub version for python3-ds flavors, because newer versions are incompatible with tensorflow 1.13.1
- Add local githooks to protect master branch
- Fix path in google-cloud-build/download_config.sh
> Pin tensorflow_hub version for python3-ds flavors and add local githooks to protect master

- exaudfclient/base/build_local_all.sh
- exaudfclient/base/javacontainer/ExaWrapper.java
- exaudfclient/base/javacontainer/javacontainer.cc
- tests/lib/exatest/clients/odbc.py
- tests/lib/udf/__init__.py
- tests/test/java/general.py
- tests/test/python/general.py
- The cleanup call in the Java UDF was in the same method as the run call. If the run call failed it bailed out of the method with an exception and didn't call cleanup.
- We extracted the cleanup part of the method into it own method and call this from the C++ as the protocol it demands
- For the test that cleanup is called after run fails, we could not use pyodbc, because it truncates the error messages. As such, we added query_via_exaplus to the test lib and used it to execute the query with exaplus.
> Fix missing cleanup call if run fails in Java-UDFs

- .current_gitmodules
- exaslct_src/exaslct/lib/tasks/export/export_container_base_task.py
Docker on MacOSX seems to return multiple lines at once when streaming API call logs. This patch extends the API of all LogHandlers with the function handle_log_lines to accept multiple lines. The AbstractLogHandler does the decoding and splitting of the lines and feeds them into the method handle_log_line.
The DockerRegistryImageChecker used before its own method to parse the log, it now uses a specific implementation of the LogHandler which simplifies this step.
> Handle multiple lines at once in LogHandlers

- exaudfclient/base/python/python3/python_ext_dataframe.cc
- find_duplicate_error_codes.sh
- tests/test/python3/dataframe.py
Solves https://github.com/exasol/script-languages-release/issues/67
Additional changes:
- Refactoring of emit python_ext_dataframe.cc 
- Additional error codes for python_ext_dataframe.cc
- Explicit error message for dataframes with datetime64 columns which are not datetime64[ns]
- Additional tests for single column dataframe emits
- Exclude tests/test directory from duplicate error code search
> Fix error when emitting only one Timestamp column in a dataframe

- exaslct_src/exaslct/lib/tasks/test/test_runner_db_test_task.py
- exaslct_src/exaslct/lib/tasks/upload/language_definition.py
- exaslct_src/test/resources/test-flavor/flavor_base/language_definition
- exaslct_src/test/resources/test-flavor/flavor_base/testconfig
- exaslct_src/test/test_generate_language_activation.py
- flavors/python3-ds-EXASOL-6.0.0/flavor_base/testconfig
- flavors/python3-ds-EXASOL-6.1.0/flavor_base/testconfig
- flavors/python3-ds-cuda-preview-EXASOL-6.1.0/flavor_base/testconfig
- Additionally, incorporate the LanguageDefinition class into the run-db-tests to tests the generation with the flavors together and avoid regressions
- LanguageDefinition class can now add missing builtin language aliases
Fixes https://github.com/exasol/script-languages-release/issues/83
> Fix generate-language-activation for standard-EXASOL-7.0.0

- flavors/python3-ds-EXASOL-6.0.0/flavor_base/release/Dockerfile
- flavors/python3-ds-EXASOL-6.1.0/flavor_base/release/Dockerfile
- flavors/python3-ds-cuda-preview-EXASOL-6.1.0/flavor_base/release/Dockerfile
- The package lists get stored under `/build_info/actual_installed_packages/release`
Contributes to https://github.com/exasol/script-languages-release/issues/92
> Add lists for actual installed packages to the release build step of the flavors

- exaslct_src/exaslct/lib/tasks/export/export_container_base_task.py
The following directories were excluded, because package manager are not needed in the exported container:
- /var/cache/apt
- /var/lib/apt
- /var/lib/dpkg
solves https://github.com/exasol/script-languages-release/issues/94
> Exclude unnecessary directories from /var during export to reduce image size

- tests/test/standard-flavor/available-packages.py
helps with https://github.com/exasol/script-languages-release/issues/103
> Add tests for standard-flavor to check if simplejson is available

- exaslct_src/test/test_docker_export.py
- flavors/python3-ds-EXASOL-6.0.0/flavor_base/udfclient_deps/Dockerfile
- flavors/python3-ds-EXASOL-6.1.0/flavor_base/udfclient_deps/Dockerfile
- flavors/python3-ds-cuda-preview-EXASOL-6.1.0/flavor_base/udfclient_deps/Dockerfile
- tests/test/python/getpass.py
- tests/test/python3/getpass.py
- Add test for getpass.getuser for python and python3 UDFs
- Furthermore, fix unstable list comparison in exaslct_src/test/test_docker_export.py 
Related to https://github.com/exasol/script-languages-release/issues/116
> Add NGA default uid to the passwd of the flavors

- ext/scripts/install_scripts/install_via_pip.pl
We add the option --use-deprecated=legacy-resolver to install_via_pip.pl to enable the legacy dependency resolver to get our flavors temporarily working again with pip 20.3. Until pip 21.0, we need to change the python dependencies in a way to fix all conflicts, see https://github.com/exasol/script-languages-release/issues/150.
> Use legacy resolver for pip in install_via_pip.pl

- exaslct
- google-cloud-build/ci-scripts/scripts/build.sh
- google-cloud-build/ci-scripts/scripts/check_build.sh
The exit code of the python script was hidden by the pipe to tee. I added `set -o pipefail` before running the python script to get the exit code of the failing command in the pipe.
Part of https://github.com/exasol/script-languages-release/issues/167
>  Fix the exit code of the exaslct start script

- ext/scripts/install_scripts/install_python2.7_pip.sh
The download url for get-pip.py changed and needed to be changed.
Closes https://github.com/exasol/script-languages-release/issues/201
> Fix url for get-pip.py in install_python2.7_pip.sh

- flavors/python-3.6-minimal-EXASOL-6.2.0/FLAVOR_DESCRIPTION.md
Fixed broken link in flavor description of Python-3.6-minimal-EXASOL-6.2.0
> #264: Fixed broken link in flavor description

- tests/test/generic/types.py
Root cause analysis:
now() was executed 3x in test TestEcho.test_echo_timestamp(),
once for each of the 3 variables. If millisecond changed during
first and second invocation, x1 and x2 had different values.
Solution:
Store now in a temporary table, and read value from there.
> Fix timestamp test (#230)

- tests/test/python3-no-python2/verify_python2.py
Returns:
```
(u'/buckets/bfsdefault/default/EXAClusterOS/ScriptLanguages-standard-exasol-7.0.0-20201109/usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so\n/buckets/bfsdefault/default/EXAClusterOS/ScriptLanguages-standard-exasol-7.0.0-20201109/usr/lib/x86_64-linux-gnu/libpython2.7.so\n/buckets/bfsdefault/default/EXAClusterOS/ScriptLanguages-standard-exasol-7.0.0-20201109/exaudf/_solib_k8/_U@python2_S_S_Cpython2___Uexternal_Spython2_Susr_Slib_Spython2.7_Sconfig-x86_U64-linux-gnu/libpython2.7.so\n',)
```
I am confused. This looks like it comes from the test spawn environment. But shouldn't 
```
./exaslct run-db-test ...
```
test the current flavor?
@tkilias please help!
Addendum: I assume this is the standard flavor of the docker db, however in run-db-test we upload another bucket, …
> #284 Added test for verification of removal of Python2

- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
Removed python-distutils-extra package from python-3.6-minimal-EXASOL-6.2.0 flavor
> #293: Removed unused package from from python-3.6-minimal-EXASOL-6.2.0 flavor

- flavors/python-3.6-data-science-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
We are using currently version 2021011918.04.1, but the version in the Ubuntu repositories has jumped to 2021011918.04.2.
> #362: Update ca-certificates package.

- ext/scripts/install_scripts/install_python2.7_pip.sh
- ext/scripts/install_scripts/install_python3.6_pip.sh
- ext/scripts/install_scripts/install_python3.7_pip.sh
- ext/scripts/install_scripts/install_python3.8_pip.sh
- ext/scripts/list_installed_scripts/list_installed_pip.sh
RCA:
1. pip install with --no-cache-dir works, no cache is beeing created
2. pip installation itself creates already a cache dir with 2 packages: 'http' and 'selfcheck'
3. "pip list" also creates a pip cache
Solution:
1. Remove cache directory after pip installation (No option was found to suppress creation of cache directory during pip installation)
2. Apply no-cache-dir for pip list
> #395: Avoid creating wheel cache in install_via_pip

- exaudfclient/base/javacontainer/BUILD
JavaContainer Bazel Build file needs to use Python3 instead of Python2.
> #415: Fix build break

- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
CVE-2022-27191 is an issue in Go. Which will be installed only together with Trivy.
> #562: Ignored CVE-2022-27191

- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
Related to https://github.com/exasol/script-languages-release/issues/623
> #623: Removed CVE-2021-43816 from ignore list

- flavors/python-3.6-data-science-cuda-EXASOL-6.2.0/flavor_base/build_deps/Dockerfile
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/build_deps/Dockerfile
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/build_deps/Dockerfile
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/Dockerfile
related to https://github.com/exasol/script-languages-release/issues/648
1. Created new S3 Bucket s3://exasol-script-languages-dependencies and deployed swig-2.0.4.tar.gz there
2. Use this new Bucket instead of GCloud
> #648: Moved swig-2.0.4.tar.gz to AWS

- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/security_scan/.trivyignore
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/security_scan/.trivyignore
related to https://github.com/exasol/script-languages-release/issues/727
> #727: Ignore  CVE-2022-23960

- .github/workflows/check_bazel_tests.yml
- .github/workflows/test_package_management_scripts.yaml
- ext/scripts/install_scripts/install_nvidia_driver_libs.sh
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/build_deps/Dockerfile
- flavors/python-3.6-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/build_deps/Dockerfile
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.7-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages_python
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/base_test_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/Dockerfile
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
- tests/Dockerfile
related to https://github.com/exasol/script-languages-release/issues/740
1. Update Ubuntu 18.04/20.04 binutils/ca-certificates/Python3.7 packages
2. Fixed a shellcheck finding (found by a newer version of shellcheck)
3. Upgraded Bazel in all flavors and GH Workflow
4. Updated dependencies in TestContainer
> #740 update ca certificates

- poetry.lock
- pyproject.toml
- test_container/tests/test/r/network.py
Related to https://github.com/exasol/script-languages-release/issues/805
After upgrading to R 4.3 putting a column from the UDFContext directly into the require function doesn't work.
> #805: Upgraded r-4-minimal flavor to R 4.3 and Ubuntu 22.04

- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/security_scan/.trivyignore
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/language_deps/packages/conda_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/security_scan/.trivyignore
- poetry.lock
Related to https://github.com/exasol/script-languages-release/issues
> #827: Update packages and ignore kernel CVEs

- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
- scripts/update_apt_package_in_package_list.sh
- test_container/build/deps/requirements.txt
Related to https://github.com/exasol/script-languages-release/issues/847
> #847: Updated packages and ignored Kernel CVEs

- test_container/tests/test/standard-flavor/all/import_modules.py
Related to https://github.com/exasol/script-languages-release/issues/857
> #857: Updated R to 4.3 and the R package in standard 7.1 flavor

- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore
- flavors/python-3.8-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/security_scan/.trivyignore
- flavors/template-Exasol-all-python-3.10/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-conda/flavor_base/security_scan/.trivyignore
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/nvidia_driver_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.8-cuda-conda/flavor_base/security_scan/.trivyignore
Related to https://github.com/exasol/script-languages-release/issues/879
1.  locales|2.31-0ubuntu9.14|2.31-0ubuntu9.15
2. Ignore some (kernel related) CVE's: 
- CVE-2024-26583
- CVE-2024-26828
- CVE-2024-26865
> #879: Package update

- ext/scripts/install_scripts/install_via_r_remotes.pl
related to https://github.com/exasol/script-languages-release/issues/856
> #856: Changed mirror for installing R packages

- test_container/tests/test/java/java_modules.py
Since we are now using ITDE 3.0.0, we need to switch the bucketfs port which was changed to `2580` in https://github.com/exasol/integration-test-docker-environment/releases/tag/2.0.0. See https://github.com/exasol/integration-test-docker-environment/issues/308
> Fixed Java module test

- .github/workflows/check_bazel_tests.yml
- exaudfclient/base/exaudflib/test/BUILD
- exaudfclient/base/exaudflib/test/script_data_transfer_objects_test.cpp
- exaudfclient/base/exaudflib/test/script_option_lines_test.cpp
- exaudfclient/base/javacontainer/test/cpp/javacontainer_test.cc
related to https://github.com/exasol/script-languages-release/issues/652
> #652: Started unit tests for script option lines parser

- exaslct_scripts/exaslct.sh
- flavors/template-Exasol-all-python-3.10/flavor_base/language_deps/packages/apt_get_packages
- poetry.lock
- pyproject.toml
- test_container/build/Dockerfile
- test_container/tests/test/disabled/search.py
- test_container/tests/test/generic/dynamic_input.py
- test_container/tests/test/generic/performance.py
- test_container/tests/test/generic/unicode.py
- test_container/tests/test/java/unicode.py
- test_container/tests/test/performance/python_set_emit_consume_large_string_columns.py
- test_container/tests/test/python3/all/getpass.py
- test_container/tests/test/python3/all/unicode.py
related to https://github.com/exasol/script-languages-release/issues/939
> #939 updated exaslct,slcci&slccisetup

- exaudfclient/.bazelrc
- exaudfclient/BUILD
- exaudfclient/README.md
- exaudfclient/build_local_all.sh
- exaudfclient/visualize_all.sh
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/base_test_build_run/Dockerfile
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/build_run/Dockerfile
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/language_definition
- flavors/template-Exasol-all-python-3.10-cuda-conda/flavor_base/base_test_build_run/Dockerfile
- flavors/template-Exasol-all-python-3.10-cuda-conda/flavor_base/build_run/Dockerfile
- flavors/template-Exasol-all-python-3.10-cuda-conda/flavor_base/language_definition
- flavors/template-Exasol-all-python-3.10/flavor_base/base_test_build_run/Dockerfile
- flavors/template-Exasol-all-python-3.10/flavor_base/build_run/Dockerfile
- flavors/template-Exasol-all-python-3.10/flavor_base/language_definition
related to https://github.com/exasol/script-languages-release/issues/944
> #944: Renamed exaudfclient_py3_bin -> exaudfclient_bin

- exaudfclient/base/javacontainer/script_options/BUILD
- exaudfclient/base/javacontainer/script_options/converter.cc
- exaudfclient/base/javacontainer/script_options/parser_ctpg_script_importer.cc
- exaudfclient/base/javacontainer/script_options/string_ops.cc
- exaudfclient/base/javacontainer/script_options/string_ops.h
- exaudfclient/base/javacontainer/script_options/test/BUILD
- exaudfclient/base/javacontainer/script_options/test/string_ops_tests.cc
- exaudfclient/base/javacontainer/test/cpp/javacontainer_test.cc
- exaudfclient/base/javacontainer/test/cpp/javavm_test.cc
Related to https://github.com/exasol/script-languages-release/issues/989
> #989: Trim script class and import script options

- exaudfclient/base/script_options_parser/ctpg/script_option_lines_ctpg.cc
- exaudfclient/base/script_options_parser/ctpg/test/script_option_lines_test.cpp
related to https://github.com/exasol/script-languages-release/issues/988
Also fixes a bug in the parser implementation which could have passed more than one line to the parser.
> #988: Improved error message from CTPG parser.

- exaudfclient/base/javacontainer/script_options/converter.cc
- exaudfclient/base/javacontainer/script_options/parser_ctpg.cc
- exaudfclient/base/javacontainer/script_options/string_ops.cc
- exaudfclient/base/javacontainer/script_options/string_ops.h
- exaudfclient/base/javacontainer/script_options/test/converter_test.cc
- exaudfclient/base/javacontainer/script_options/test/string_ops_tests.cc
- exaudfclient/base/javacontainer/test/cpp/javacontainer_extractor_v2_test.cc
- exaudfclient/base/javacontainer/test/cpp/javacontainer_test.cc
related to https://github.com/exasol/script-languages-release/issues/990
> #990:Implemented escape sequence for jar option with trailing whitespaces

- flavors/test-Exasol-8-cuda-ml/flavor_base/testconfig
- test_container/tests/test/python3-cuda-flavor/numba.py
- test_container/tests/test/python3-cuda-flavor/pytorch.py
related https://github.com/exasol/script-languages-release/issues/1036
> #1036: Added pytorch and numba integration test compatible with CPU only VM

- poetry.lock
- pyproject.toml
related to https://github.com/exasol/script-languages-release/issues/1057
> #1057: Updated exaslct dependency + poetry lock

- test_container/tests/test/pandas/all/dataframe_memory_leak.py
related to https://github.com/exasol/script-languages-release/issues/1060
We suspect that GC is not finished when the test reads the memory snapshot => Sleep 1s after triggerer GC might fix this problem.
I ran the AWS Build with https://github.com/exasol/script-languages-release/pull/1061 3x and it worked. So the workaround looks promising.
> Added sleep in dataframe_memory_leak test after gc collection

- test_container/tests/test/standard-flavor/all/python/import_modules.py
Ignore those sub-modules because they include modified version of pytest.
> Ignore submodules `joblib.testing` and `joblib.test`

- flavors/test-Exasol-8-cuda-ml/flavor_base/flavor_base_deps/packages/conda_packages
- flavors/test-Exasol-8-cuda-ml/flavor_base/release/Dockerfile
- flavors/test-Exasol-8-cuda-ml/flavor_base/security_scan/.trivyignore
related to https://github.com/exasol/script-languages-release/issues/1145
related to https://github.com/exasol/script-languages-release/issues/1147
- also update `pytorch` to 2.7.0
> #1145/#1147: Ignore CVE-2025-47273 and remove unnecessary copy

- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-8-python-3.10-cuda-conda/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/conda_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10-conda/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/build_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/flavor_base_deps/packages/apt_get_packages
- flavors/template-Exasol-all-python-3.10/flavor_base/udfclient_deps/packages/apt_get_packages
- flavors/test-Exasol-8-cuda-ml/flavor_base/conda_deps/packages/apt_get_packages
- flavors/test-Exasol-8-cuda-ml/flavor_base/flavor_base_deps/packages/apt_get_packages
- poetry.lock
Related to https://github.com/exasol/script-languages-release/issues/1153
Related to https://github.com/exasol/script-languages-release/issues/1152
Fixes
* CVE-2025-47287 in transitive productive dependency `tornado` via `luigi` by updating `tornado` to version `6.5.1`
* CVE-2025-47273 in transitive dev dependency `setuptools` via `exasol-toolbox`, `bandit`, `stevedore` by updating `setuptools` to version `80.9.0`
> #1152: Fixed vulnerabilities by updating dependencies
